# Generated by Django 5.2 on 2025-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0002_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="pages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
