# Generated by Django 5.2 on 2025-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0003_chapter_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="artist",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="manga",
            name="author",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="manga",
            name="released_year",
            field=models.CharField(default="2022", max_length=4),
        ),
        migrations.AddField(
            model_name="manga",
            name="status",
            field=models.CharField(default="Ongoing", max_length=50),
        ),
        migrations.AddField(
            model_name="manga",
            name="type",
            field=models.CharField(default="Manhwa", max_length=50),
        ),
    ]
