# Generated by Django 5.2 on 2025-12-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0004_manga_artist_manga_author_manga_released_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manga",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
