# Generated by Django 5.2 on 2025-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0005_manga_is_featured_manga_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
