# Generated by Django 5.2 on 2025-12-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0007_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="cover_image_file",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
