# Generated by Django 5.2 on 2025-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0008_manga_cover_image_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="manga",
            name="genres",
        ),
        migrations.AddField(
            model_name="manga",
            name="genres",
            field=models.ManyToManyField(blank=True, to="mangas.genre"),
        ),
    ]
