# Generated by Django 5.2 on 2025-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0009_genre_remove_manga_genres_manga_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="banner_image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="manga",
            name="banner_image_file",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
