# Generated by Django 5.2 on 2025-12-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0010_manga_banner_image_manga_banner_image_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("views", models.IntegerField(default=0)),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_views",
                        to="mangas.manga",
                    ),
                ),
            ],
            options={
                "unique_together": {("manga", "date")},
            },
        ),
    ]
